/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-qrencode.h
 #	source generated by 4D Plugin Wizard
 #	Project : qrencode
 #	author : miyako
 #	2019/10/10
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_QRENCODE_H
#define PLUGIN_QRENCODE_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_BLOB.h"
#include "C_LONGINT.h"

#include "4DPlugin-JSON.h"
#include "json.h"

#pragma mark -

void qrencode(PA_PluginParameters params);
void qrcode_array(PA_PluginParameters params);

enum output_type_t {
    QR_OUTPUT_PNG,
    QR_OUTPUT_SVG
};

#ifdef _WIN32
extern "C" { FILE __iob_func[3] = { *stdin,*stdout,*stderr }; }
#endif

#include "qrencode.h"
#include "png.h"

#define INCHES_PER_METER (100.0/2.54)

#define QR_Mode_Unicode 0x0000
#define QR_Mode_Kanji   0x0001
#define QR_Mode_Micro   0x0002
#define QR_Mode_Swiss   0x0004

void toSVG(QRcode *qr, int margin, int size, int dpi, PA_ObjectRef o);
void toPNG(QRcode *qr, int margin, int size, int dpi, PA_ObjectRef o);

void toSVGs(QRcode *qr, int margin, int size, int dpi, int pos, PA_CollectionRef c);
void toPNGs(QRcode *qr, int margin, int size, int dpi, int pos, PA_CollectionRef c);

void write_data_fn(png_structp png_ptr, png_bytep buf, png_size_t size);
void output_flush_fn(png_structp png_ptr);

#endif /* PLUGIN_QRENCODE_H */
